# Generated by Django 6.1.1 on 2026-09-28 15:55

import apps.accounts.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='email')),
                ('nombre', models.CharField(blank=True, max_length=150, verbose_name='nombre')),
                ('telefono', models.CharField(blank=True, max_length=32, verbose_name='teléfono')),
                ('rol', models.CharField(choices=[('paciente', 'Paciente'), ('recepcion', 'Recepcion'), ('medico', 'Médico'), ('admin', 'Administrador')], default='paciente', max_length=20, verbose_name='rol')),
                ('email_verified', models.BooleanField(default=False, verbose_name='email verificado')),
                ('must_change_password', models.BooleanField(default=False, verbose_name='debe cambiar la contraseña')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='acceso al admin')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='último acceso')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='alta')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'ordering': ('-date_joined',),
            },
            managers=[
                ('objects', apps.accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='EmailVerificationCode',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('purpose', models.CharField(choices=[('registro', 'Registro'), ('cambio_email', 'Cambio de email'), ('reset_password', 'Restablecer contraseña')], default='registro', max_length=20, verbose_name='propósito')),
                ('code_hash', models.CharField(max_length=255, verbose_name='hash del código')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='creado')),
                ('expires_at', models.DateTimeField(verbose_name='expira')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='usado')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='intentos')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'código de verificación',
                'verbose_name_plural': 'códigos de verificación',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['rol'], name='idx_usuario_rol'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email_verified'], name='idx_usuario_verificado'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('is_staff', True), ('rol', 'paciente'), _negated=True), name='paciente_sin_acceso_admin'),
        ),
        migrations.AddIndex(
            model_name='emailverificationcode',
            index=models.Index(fields=['user', 'purpose'], name='idx_codigo_usuario'),
        ),
    ]
